### PR TITLE
Hide age from title when year is not set

### LINKED ISSUE #52: Birthday without age shows 43
_Original author: alex.je...@gmail.com (April 23, 2013 08:42:12)_

<b>What steps will reproduce the problem?</b>
1.it shows even with original and custom labels 
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
It should show without age. 

<b>What version of the product are you using? On what operating system?</b>
1.13 (14) on custom rom SlimBean 4.2.2 build 3

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/birthday-adapter/issues/detail?id=50_

### LINKED ISSUE #79: Ages (in parenthesis) not updating/not removed after removing year from contact's birthday
Hi, great app! 
A bug - I removed the year and left just the month and day in the birthday - but the app is still showing the 'age' in parenthesis.
Thanks
Larry

### PR DESCRIPTION
**Pull request by edigiacomo**
Fix #79
Fix #52

### CODE REVIEW

**Comment by edigiacomo** [comment]
Some screenshots:

contact-with-year-small

contact-without-year-small

calendar-small

**Comment by dschuermann** [comment]
great work, thanks! 👍

**Comment by tasn** [comment]
@dschuermann, can you please release a new version of birthday-calendar so it's built by f-droid?
Piggy backing on this issue because it's the fix I care about, sorry for the mess. :)
Thanks.

**Comment by dschuermann** [comment]
@tasn Sry for the delays. I will try to free up some time next week.

**Comment by tasn** [comment]
Thanks!

**Pull request merged**
